Repository Uriel-98/Avocado-ISPC, pull requests merged in 2023-09, with the labels that each got.

#7 Actualización de Readme
  README.md
Labels: documentation

#27 Creación carpeta Documentacion y Archivo IEEE830
  Documentacion/IEEE830-Avocado.pdf
Labels: documentation, Task

#35 agregué mi activity y cree la carpeta java y layout que no estaba
  .idea/gradle.xml
  .idea/misc.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/proyectoavocado/AddRecipeActivity.java
  app/src/main/res/layout/activity_add_recipe.xml
Labels: FrontEnd

#36 Navbar y menú para todas las vistas
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/proyectoavocado/PerfilActivity.java
  app/src/main/res/drawable/check_icon.png
  app/src/main/res/drawable/estrella_icono.png
  app/src/main/res/drawable/home_icono.png
  app/src/main/res/drawable/icono_perfil.png
  app/src/main/res/drawable/logo_nombre.png
  app/src/main/res/drawable/logo_palta.png
  app/src/main/res/drawable/lupa_icono.png
  app/src/main/res/drawable/mas_icono.png
  app/src/main/res/drawable/persona_icono.png
  app/src/main/res/drawable/x_icon.png
  app/src/main/res/font/roboto.xml
  app/src/main/res/font/roboto_black.xml
  app/src/main/res/font/roboto_bold.xml
  app/src/main/res/font/roboto_thin.ttf
  app/src/main/res/layout/activity_perfil.xml
  app/src/main/res/values/font_certs.xml
  app/src/main/res/values/preloaded_fonts.xml
Labels: FrontEnd, Task

#39 Activity Iniciar Sesión estructura vista
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/proyectoavocado/IniciarSesionActivity.java
  app/src/main/res/layout/activity_iniciar_sesion.xml
Labels: FrontEnd

#41 Activity Agregar Receta estructura completa
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/proyectoavocado/AgregaRecetaActivity.java
  app/src/main/res/drawable/batidor_icon.png
  app/src/main/res/drawable/clock_icon.png
  app/src/main/res/drawable/pen_icon.png
  app/src/main/res/layout/activity_add_recipe.xml
  app/src/main/res/layout/activity_agrega_receta.xml
  build.gradle
Labels: FrontEnd, Task

#42 Activity perfil estructura layout
  app/src/main/res/layout/activity_perfil.xml
Labels: FrontEnd, Task

#46 Activities Inicio y Contacto
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/proyectoavocado/ContactoActivity.java
  app/src/main/java/com/example/proyectoavocado/InicioActivity.java
  app/src/main/res/layout/activity_contacto.xml
  app/src/main/res/layout/activity_inicio.xml
Labels: FrontEnd, Task
