Repository Uriel-98/Avocado-ISPC, pull requests merged in 2023-10, with the labels that each got.

#49 Creación de Activity Vista Detallada de Receta
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/proyectoavocado/VistaDetalladaActivity.java
  app/src/main/res/layout/activity_agrega_receta.xml
  app/src/main/res/layout/activity_vista_detallada.xml
Labels: FrontEnd, Task

#50 Corrección de errores
  app/src/main/res/layout/activity_iniciar_sesion.xml
  app/src/main/res/layout/activity_inicio.xml
  app/src/main/res/layout/activity_perfil.xml
  app/src/main/res/layout/activity_registrarse.xml
  app/src/main/res/layout/activity_vista_detallada.xml
Labels: bug, invalid, FrontEnd

#52 Corrección vista Inicio
  .idea/deploymentTargetDropDown.xml
  app/src/main/res/layout/activity_inicio.xml
Labels: FrontEnd

#60 Agregación del Script de la BD
  Database/bd_avocado.sql
Labels: DataBase

#61 Casos de prueba de la app
  Documentacion/Casos de Prueba.xlsx - Hoja 1.pdf
Labels: documentation

#62 Agrego diagrama de casos de uso y diagrama de clases
  .idea/deploymentTargetDropDown.xml
  Documentacion/Diagrama de casos de uso.jpg
  Documentacion/Diagrama de clases.jpg
  app/src/main/res/layout/activity_registrarse.xml
Labels: documentation

#63 Activity Registrarse arreglada
  app/src/main/java/com/example/proyectoavocado/ContactoActivity.java
  app/src/main/java/com/example/proyectoavocado/favoritesActivity.java
  app/src/main/res/layout/activity_favorites.xml
  app/src/main/res/layout/activity_registrarse.xml
Labels: bug

#75 cree las cards por separado, esta el dialog de eliminar cuenta pero no la logica
  .gitignore
  app/build.gradle
  app/src/main/java/com/example/proyectoavocado/FeedActivity.java
  app/src/main/java/com/example/proyectoavocado/ModificarPerfilActivity.java
  app/src/main/java/com/example/proyectoavocado/Receta.java
  app/src/main/java/com/example/proyectoavocado/RecipeCardAdapter.java
  app/src/main/res/layout/activity_feed.xml
  app/src/main/res/layout/dialog_eliminar_cuenta.xml
  app/src/main/res/layout/receta_feed_card.xml
  app/src/main/res/values/strings.xml
Labels: FrontEnd, BackEnd, DataBase, Task, Config

#76 card para perfil, adaptador para la card del perfil y logica para traer los datos de labd, logica para eliminar la cuenta
  app/src/main/java/com/example/proyectoavocado/ModificarPerfilActivity.java
  app/src/main/java/com/example/proyectoavocado/PerfilActivity.java
  app/src/main/java/com/example/proyectoavocado/PerfilRecipeCardAdapter.java
  app/src/main/java/com/example/proyectoavocado/Receta.java
  app/src/main/java/com/example/proyectoavocado/favoritesActivity.java
  app/src/main/res/layout/activity_contacto.xml
  app/src/main/res/layout/activity_perfil.xml
  app/src/main/res/layout/receta_feed_card.xml
  app/src/main/res/layout/receta_perfil_card.xml
Labels: FrontEnd, BackEnd, DataBase, Task

#89 Gaston dev2023
  Backend/routes/registro.js
  app/src/main/java/com/example/proyectoavocado/RegistrarseActivity.java
  app/src/main/res/layout/activity_registrarse.xml
Labels: BackEnd, DataBase

#90 Cards dinámicas para el feed, diálogos para modificar receta y código reciclable.
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/proyectoavocado/FeedActivity.java
  app/src/main/java/com/example/proyectoavocado/IniciarSesionActivity.java
  app/src/main/java/com/example/proyectoavocado/ModificarRecetaActivity.java
  app/src/main/java/com/example/proyectoavocado/PerfilActivity.java
  app/src/main/java/com/example/proyectoavocado/controllers/Categoria.java
  app/src/main/java/com/example/proyectoavocado/controllers/Ingrediente.java
  app/src/main/java/com/example/proyectoavocado/controllers/Paso.java
  app/src/main/java/com/example/proyectoavocado/controllers/Receta.java
  app/src/main/java/com/example/proyectoavocado/controllers/RecetaControl.java
  app/src/main/java/com/example/proyectoavocado/controllers/Usuario.java
  app/src/main/java/com/example/proyectoavocado/controllers/UsuarioControl.java
  app/src/main/java/com/example/proyectoavocado/reciclesAdaptadores/CategoriaRecipeAdapter.java
  app/src/main/java/com/example/proyectoavocado/reciclesAdaptadores/IngredienteRecipeAdapter.java
  app/src/main/java/com/example/proyectoavocado/reciclesAdaptadores/PasosRecetaRecipeAdapter.java
  app/src/main/java/com/example/proyectoavocado/reciclesAdaptadores/PerfilRecipeCardAdapter.java
  app/src/main/java/com/example/proyectoavocado/reciclesAdaptadores/RecipeCardAdapter.java
  app/src/main/res/color/radio_button_selector.xml
  app/src/main/res/layout/activity_modificar_receta.xml
  app/src/main/res/layout/activity_vista_detallada.xml
  app/src/main/res/layout/categoria_layout.xml
  app/src/main/res/layout/dialog_agregar_ingrediente.xml
  app/src/main/res/layout/dialog_agregar_paso.xml
  app/src/main/res/layout/dialog_categoria.xml
  app/src/main/res/layout/dialog_editar_descripcion_coccion_dificultad.xml
  app/src/main/res/layout/dialog_modificar_titulo_receta.xml
  app/src/main/res/layout/ingrediente_receta.xml
  app/src/main/res/layout/pasos_receta.xml
  app/src/main/res/layout/radio_btn_categoria.xml
  app/src/main/res/values/strings.xml
Labels: FrontEnd, BackEnd, DataBase, Task

#91 Corrección modificar receta y menú receta
  app/src/main/java/com/example/proyectoavocado/ModificarRecetaActivity.java
  app/src/main/java/com/example/proyectoavocado/VistaDetalladaActivity.java
  app/src/main/res/layout/menu_receta.xml
Labels: FrontEnd, BackEnd, DataBase, Task

#94 Lógica para agregar receta y corrección al layout
  app/src/main/java/com/example/proyectoavocado/AgregaRecetaActivity.java
  app/src/main/java/com/example/proyectoavocado/reciclesAdaptadores/CategoriaRecipeAdapter.java
  app/src/main/res/layout/activity_agrega_receta.xml
Labels: FrontEnd, BackEnd, DataBase, Task

#97 Gaston dev2023
  app/src/main/java/com/example/proyectoavocado/IniciarSesionActivity.java
  app/src/main/java/com/example/proyectoavocado/RegistrarseActivity.java
  app/src/main/res/layout/dialog_registro_incorrecto.xml
Labels: FrontEnd, BackEnd, DataBase

#98 Imágenes para perfil de los integrantes y lógica modificar receta
  app/src/main/java/com/example/proyectoavocado/ModificarRecetaActivity.java
  app/src/main/res/drawable/aylen_perfil.jpg
  app/src/main/res/drawable/flor_perfil.jpg
  app/src/main/res/drawable/gaston_perfil.jpg
  app/src/main/res/drawable/hernan_perfil.jpg
  app/src/main/res/drawable/tay_perfil1.jpg
  app/src/main/res/drawable/uriel_perfil.jpg
  app/src/main/res/drawable/yani_perfil.jpg
  app/src/main/res/layout/activity_modificar_receta.xml
Labels: FrontEnd, BackEnd, DataBase, Task

#102 Gaston dev2023
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/assets/avocado_lotti.json
  app/src/main/java/com/example/proyectoavocado/AcercaActivity.java
  app/src/main/java/com/example/proyectoavocado/FeedActivity.java
  app/src/main/res/layout/activity_acerca.xml
  app/src/main/res/values-night/themes.xml
Labels: FrontEnd

#106 Acerca de completo y botones funcionando, boton cancerlas en eliminar cuenta funcionando
  Backend/routes/usuario.js
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/proyectoavocado/AcercaActivity.java
  app/src/main/java/com/example/proyectoavocado/AgregaRecetaActivity.java
  app/src/main/java/com/example/proyectoavocado/ModificarPerfilActivity.java
  app/src/main/java/com/example/proyectoavocado/VistaDetalladaActivity.java
  app/src/main/java/com/example/proyectoavocado/reciclesAdaptadores/RecipeCardAdapter.java
  app/src/main/res/layout/activity_acerca.xml
  app/src/main/res/layout/dialog_editar_descripcion_coccion_dificultad.xml
  app/src/main/res/layout/dialog_modificar_titulo_receta.xml
Labels: bug, enhancement, FrontEnd, BackEnd, DataBase, Config

#107 no esta funcionando agregar los pasos al crear receta
  app/src/main/java/com/example/proyectoavocado/AgregaRecetaActivity.java
  app/src/main/java/com/example/proyectoavocado/VistaDetalladaActivity.java
  app/src/main/res/layout/activity_agrega_receta.xml
  app/src/main/res/values/strings.xml
Labels: help wanted, FrontEnd, BackEnd, DataBase, Task

#109 Modifico diagrama de casos de uso y diagrama de clases con las correcciones requeridas
  Documentacion/Diagrama de casos de uso.jpg
  Documentacion/Diagrama de clases.jpg
Labels: documentation

#110 tratando de hacer solucionar modificar receta
  app/src/main/java/com/example/proyectoavocado/ModificarRecetaActivity.java
  app/src/main/java/com/example/proyectoavocado/VistaDetalladaActivity.java
  app/src/main/java/com/example/proyectoavocado/reciclesAdaptadores/IngredienteRecipeAdapter.java
  app/src/main/java/com/example/proyectoavocado/reciclesAdaptadores/PasoViewAdapter.java
Labels: bug, FrontEnd, BackEnd, DataBase, Task
